git:
  depth: 3
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
- '7'
- '6'
- '4'
env:
  - PKG_CMD="npm"
  - PKG_CMD="yarn"
before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm set loglevel error
  - npm set progress false
  - 'if [ $PKG_CMD = "yarn" ]; then npm i -g yarn@0.21.3 ; fi'
install:
  - $PKG_CMD install
script:
  - 'if [ -n "${LINT-}" ]; then $PKG_CMD run lint ; fi'
  - 'if [ -z "${LINT-}" ]; then $PKG_CMD run ci ; fi'
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true PKG_CMD="npm"
