git:
  depth: 3
sudo: false
language: node_js
cache:
  directories:
  - node_modules

script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -z "${LINT-}" ]; then npm run ci ; fi'

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "node"
      env: LINT=true
      
    - os: linux
      node_js:
      - '7'
      - '6'
      - '4'
      - '0.12'
      - '0.10'

    - os: osx
      language: node_js
