git:
  depth: 3
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
- '7'
- '6'
- '4'
env:
  global:
    - BABEL_ENV=test
  matrix:
    - PKG_CMD="npm"
    - PKG_CMD="yarn"
before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm set loglevel error
  - npm set progress false
  - 'if [ $PKG_CMD = "yarn" ]; then curl -o- -L https://yarnpkg.com/install.sh | bash && PATH=$HOME/.yarn/bin:$PATH ; fi'
install:
  - $PKG_CMD install
script:
  - 'if [ -n "${LINT-}" ]; then $PKG_CMD run lint ; fi'
  - 'if [ -n "${DATA_CHECK-}" ]; then $PKG_CMD run build-data -- --check ; fi'
  - 'if [ -n "${SMOKE_TEST-}" ]; then node scripts/smoke-test.js ; fi'
  - 'if [ -z "${LINT-}" ] && [ -z "${DATA_CHECK-}" ] && [ -z "${SMOKE_TEST-}" ]; then $PKG_CMD run test-ci ; fi'
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true PKG_CMD="npm"
    - node_js: "node"
      env: DATA_CHECK=true PKG_CMD="npm"
    - node_js: "node"
      env: SMOKE_TEST=true PKG_CMD="npm"

after_success: 'if [ -z "${LINT-}" ] && [ -z "${DATA_CHECK-}" ] && [ -z "${SMOKE_TEST-}" ]; then npm run coverage-ci ; fi'
