git:
  depth: 3
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '7'
- '6'
- '4'
- '0.12'
- '0.10'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -z "${LINT-}" ]; then npm run ci ; fi'
os: [linux, osx]
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      os: linux # only lint on linux, no need to lint on os x too
      env: LINT=true
